### ISSUE TITLE
LoadAndAssign not loading all XDP programs and program array map statically initialized not populated 

### ISSUE THREAD

**Issue by vincentmli** [cilium/ebpf#1038]
**Describe the bug**

Sorry I am not sure if this is me not using this library correctly or potential bug :)

I have this https://github.com/vincentmli/go-xdpdns/tree/cookie that is  forked from https://github.com/NLnetLabs/XDPeriments/tree/master/Cookies where I initialized the program array map statically in the eBPF code instead of using the https://github.com/NLnetLabs/XDPeriments/blob/master/Cookies/xdp_dns_cookies_user.c from the original repo to populate the program array map
```
struct {
        __uint(type, BPF_MAP_TYPE_PROG_ARRAY);
        __uint(max_entries, 3);
        __uint(key_size, sizeof(uint32_t));
        __array(values, int (void *));
} jmp_rate_table SEC(".maps") = {
        .values = {
                [DO_RATE_LIMIT_IPV6] = (void *)&xdp_do_rate_limit_ipv6,
                [DO_RATE_LIMIT_IPV4] = (void *)&xdp_do_rate_limit_ipv4,
        },
};
```
but after I run the `go-xdpdns` program which basically uses ebpf-go to load and attach the XDP programs, the program array map is not populated, the only  XDP program `xdp_dns_cookies` is loaded, there are 5 XDP programs in the object file 

grep -r '^SEC(' xdp_rrl.c 
SEC("xdp-do-rate-limit-ipv6")
SEC("xdp-do-rate-limit-ipv4")
SEC("xdp-cookie-verify-ipv6")
SEC("xdp-cookie-verify-ipv4")
SEC("xdp-dns-cookies")

bpftool prog output

```
88: xdp  name xdp_dns_cookies  tag ac06a4f390b8f92b  gpl
	loaded_at 2023-05-16T08:36:11-0700  uid 0
	xlated 2144B  jited 1460B  memlock 4096B  map_ids 98,99,96,100
	btf_id 707
```

bpftool map

```
root@vincent-pc2:/home/vincent/go/src/github.com/vincentmli/go-xdpdns# bpftool map
74: lpm_trie  name exclude_v4_pref  flags 0x1
	key 8B  value 8B  max_entries 10000  memlock 163840B
75: lpm_trie  name exclude_v6_pref  flags 0x1
	key 12B  value 8B  max_entries 10000  memlock 241664B
96: prog_array  name jmp_rate_table  flags 0x0
	key 4B  value 4B  max_entries 3  memlock 4096B
	owner_prog_type xdp  owner jited
98: lpm_trie  name exclude_v6_pref  flags 0x1
	key 12B  value 8B  max_entries 10000  memlock 241664B
99: lpm_trie  name exclude_v4_pref  flags 0x1
	key 8B  value 8B  max_entries 10000  memlock 163840B
100: prog_array  name jmp_cookie_tabl  flags 0x0
	key 4B  value 4B  max_entries 3  memlock 4096B
	owner_prog_type xdp  owner jited
```
dump program array map

```
root@vincent-pc2:/home/vincent/go/src/github.com/vincentmli/go-xdpdns# bpftool map dump id 96
Found 0 elements
```

**To Reproduce**
Steps to reproduce the behavior. Please include:

git clone  https://github.com/vincentmli/go-xdpdns.git

git checkout cookie

make clean; make

./go-xdpdns --interface lo --ratelimit 10

```sh

go version go1.20.1 linux/amd64

Linux vincent-pc2 6.1.13-060113-generic #202302221342 SMP PREEMPT_DYNAMIC Wed Feb 22 15:30:01 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

Ubuntu 20.04.5 LTS \n \l
```

**Expected behavior**

**Comment by vincentmli** [comment]
sorry to re-open this, I thought maybe I had the program array map defined wrong result in program array map not populated by ebpf-go library, but after I test using https://github.com/vincentmli/XDPeriments/blob/master/Cookies/xdp_dns_cookies_user.c to load same bpf object file, the program array map is populated properly, so I think this has something to do with `LoadAndAssign`, here is the program array map:

```
struct {
        __uint(type, BPF_MAP_TYPE_PROG_ARRAY);
        __uint(max_entries, 3);
        __uint(key_size, sizeof(uint32_t));
        __uint(value_size, sizeof(uint32_t));
        __array(values, int (void *));
} jmp_rate_table SEC(".maps") = {
        .values = {
                [DO_RATE_LIMIT_IPV6] = (void *)&xdp_do_rate_limit_ipv6,
                [DO_RATE_LIMIT_IPV4] = (void *)&xdp_do_rate_limit_ipv4,
        },
};
```

**Comment by ti-mo** [comment]
See https://github.com/cilium/ebpf/discussions/578.

This is a characteristic of program arrays. If all userspace references are gone (no more pins/fds), all its entries are removed. In your program, after the call to `link.AttachXDP`, there are no more references to `objs` and the runtime is free to collect it and any resources it points to, including all *Maps. *Map has a finalizer that calls Close() on itself when it's collected, causing the underlying fd to be closed, clearing the map.

Your code has two problems:
- Due to what I wrote above, omitting Close() is an error. Uncommenting `defer objs.Close()` will make sure there's a reference to `objs` until your main returns: https://github.com/vincentmli/go-xdpdns/blob/cf67ba09050a4525a89f6041850dd63bcd956cde/main.go#LL178C22-L178C22.
- jmp_rate_table and jmp_cookie_table don't have their pinning flags set, so they won't be pinned despite setting `CollectionOptions.Maps.PinPath`. Since your program is short-lived, this always clears the prog arrays instantly.
