### ISSUE TITLE
Usage of unstable golang.org/x/exp package

### ISSUE THREAD

**Issue by akhilerm** [cilium/ebpf#1095]
`cilium/ebpf` is using the unstable `golang.org/x/exp` dependency in its codebase.  As per golang [docs](https://pkg.go.dev/golang.org/x/exp#section-readme), these packages are experimental and unstable.  The package was introduced in https://github.com/cilium/ebpf/pull/951, and more packages become dependent on `exp` in https://github.com/cilium/ebpf/pull/1069.

These are now available in the `v0.11.0` release. We noted the issue while trying to upgrade to `v0.11.0` in the kubernetes repository. https://github.com/kubernetes/kubernetes/pull/117457.

Can the experimental package be removed and use a stable golang package instead?

**Comment by aojea** [comment]
It seems there are more places importing this dependency

```sh
$ grep -r x\/exp
btf/strings.go: "golang.org/x/exp/maps"
btf/marshal.go: "golang.org/x/exp/slices"
internal/align.go:// forked from "golang.org/x/exp/constraints"
```

@lmb @ti-mo importing this dependency makes hard to import this project, can we avoid adding more code depending on it and try to remove it?

**Comment by liggitt** [comment]
Agreed, please drop the exp dependency

**Comment by brycekahle** [comment]
Since `go.mod` pins the dependency to a specific commit, the imported code won't suddenly change. Is there a concern about the contents of the imported code? These packages are used all over the ecosystem now:

Imported by:
`golang.org/x/exp/maps`: [1,472](https://pkg.go.dev/golang.org/x/exp/maps?tab=importedby)
`golang.org/x/exp/slices`: [3,893](https://pkg.go.dev/golang.org/x/exp/slices?tab=importedby)
`golang.org/x/exp/constraints`: [2,060](https://pkg.go.dev/golang.org/x/exp/constraints?tab=importedby)

**Comment by liggitt** [comment]
> Is there a concern about the contents of the imported code? 

Yes. Use of it is relying on an explicitly unstable dependency which could break in future versions, and dependents which rely on it transitively might be unable to find a version which works with all the transitive links to it.

**Comment by liggitt** [comment]
Concretely, kubernetes will not update to a version of this library which adds a transitive link to this dependency because of this

**Comment by brycekahle** [comment]
Would copying the code into this repo, with the appropriate copyright kept, satisfy your needs?

**Comment by liggitt** [comment]
copying with attribution would resolve the issue with future incompatible levels (that said, the use in this repo looks ~very minimal... reimplementing rather than copying would probably be reasonable)

**Comment by lmb** [comment]
I think there are two issues here. The first is what I'd call failure of communication: if you want us to abide with a policy which k8s wants to impose on it's dependencies you need to give more context. All I got so far was a two sentence explanation by @liggitt. Is this policy written up somewhere? Can I see the process that led to it? If we agree to the policy now, do we as maintainers of a dependencies get a say when that policy is updated? Or are we just expected to take whatever k8s decides as gospel?

The second issue is that if I understand you correctly, you want us to at least:
- Drop all use of x/exp now
- Not use x/exp in the future
Reading between the lines, you might want us to only use released versions of dependencies in the future, full stop? These policies take away a lot of freedom from us, and will cause us additional work to copy around code if we ever need something from x/exp.

**Comment by liggitt** [comment]
Apologies for the way this came across, we're not expecting folks to drop this *because* of kubernetes, but because *exp* advertises itself as an unstable dependency. Anyone accepting a transitive dependency on exp risks future gridlock and being unable to update one or more dependencies if/when parts of exp change in incompatible ways.

The issue/PR to clean up the use was not intended to be aggressive at all, we're just trying to unblock ourselves and be helpful :)

Feel free to use or discard the example PR, whichever works better for you.

> That said, we explicitly took on the x/exp dependency because things are a little up in the air right now. The parts that we're using contain a few TODOs that we'd like to benefit from when they're eventually resolved and/or when the compiler takes care of them instead. Copying the implementation(s) puts us on the hook for tracking these things ourselves, which we're simply not going to do/remember.

The only TODO I see that would apply to a reimplemented non-generic version is that any new int types would be added to constraints.Integer. I'd be happy to add a unit test to notice them if that would make the PR more acceptable.

> We'll make sure to drop x/exp when those packages move back into the stdlib. 🙂

The exp use sticking around for another 6-12 months at minimum puts downstreams trying to avoid that dependency in a difficult position. Please be aware of the tradeoff when deciding how to proceed.

**Comment by lmb** [comment]
Thanks for the context. I'm still curious whether any of this is written down somewhere? I can't be the first one to ask these questions?

> Anyone accepting a transitive dependency on exp risks future gridlock and being unable to update one or more dependencies if/when parts of exp change in incompatible ways.

Seems like this is the crux of the matter. What does this gridlock look like? Has it happened before? Why is exp worse than other unstable (aka non-v1) packages?

Looking at https://pkg.go.dev/golang.org/x/exp#section-directories you can see that x/exp actually exports a bunch of individual modules. Is depending on those OK?

Re incompatible changes. From the [discussion on math/rand v2](https://github.com/golang/go/discussions/60751):

>Once math/rand/v2 has shipped, we would tag and delete x/exp/rand. This would keep programs that already use x/exp/rand working (by reference to the tagged version or older versions of x/exp) but allow us to delete the code from the main branch of x/exp, making clear that development on it has ended.

Seems like Go team is aware of these concerns and going out of their way to make sure dependants aren't broken needlessly.

**Comment by liggitt** [comment]
> What does this gridlock look like?

Inability to update one or more dependencies (possibly blocking things like security fixes) because they use packages in exp with changes that are incompatible with exp versions already in use by other things in the build tree.

> Has it happened before?

I haven't been personally blocked by exp because we've avoided multiple transitive dependencies to it until now, but with other modules, sure.

> Why is exp worse than other unstable (aka non-v1) packages?

It explicitly advertises itself as experimental / unstable.

> Looking at https://pkg.go.dev/golang.org/x/exp#section-directories you can see that x/exp actually exports a bunch of individual modules. Is depending on those OK?

As long as the submodules have the same "unstable, can change in incompatible ways" policy, I'd avoid them as well for the same reason.

> Seems like Go team is aware of these concerns and going out of their way to make sure dependents aren't broken needlessly.

That's nice to see, but doesn't really protect against the scenario I'm concerned about where they consider a breaking change to a package's API necessary. The freedom to make those types of changes seems to be the point of the repo.

**Comment by lmb** [comment]
Here is my summary of what I've learned from your comments here and by reading up on upstream PRs:
* "Unwanted" libraries are added to [`unwanted-dependencies.json`](https://github.com/kubernetes/kubernetes/blob/master/hack/unwanted-dependencies.json) on an ad hoc basis. The criteria are fuzzy. For example, the ban on `x/exp` was added due to https://github.com/kubernetes/kubernetes/pull/118339#discussion_r1210988844 As we know from the discussion here this was due to an abundance of caution rather than a concrete problem.
* k8s doesn't actually want to depend on c/ebpf. It's a transitive dependency via libcontainer. Apparently some future version of runc will [allow dropping the reference](https://github.com/kubernetes/kubernetes/pull/117457#issuecomment-1528070248). If I understand correctly you never even execute c/ebpf code at the moment, so staying on an old version should be fine.

Based on this, I'm inclined to keep the dependency on x/exp. You're correct that the current usage is limited, but I think the question here is not whether we can drop x/exp. Rather, this is about whether we want to abide by the k8s exclusion list. Personally, I find the rules you are outlining too restrictive. If there is a well-maintained dependency that is v0 we should take it. After all we ourselves make breaking changes, but do it only when necessary.

That said, if you do end up updating your minimum version we'll be responsive if a dependency on x/exp ever does break something.

**Comment by liggitt** [comment]
> As we know from the discussion here this was due to an abundance of caution rather than a concrete problem.

Our experience has been that prevention is _far_ easier than recovery when it comes to tangled or problematic dependencies, especially when the issues can be encountered in urgent must-update-quickly scenarios around bug/security fixes.

> k8s doesn't actually want to depend on c/ebpf. It's a transitive dependency via libcontainer.

That's true, we don't want to, but we don't have a way to avoid it at the moment since we inherit it transitively from fundamental k8s dependencies.

> * Apparently some future version of runc will [allow dropping the reference](https://github.com/kubernetes/kubernetes/pull/117457#issuecomment-1528070248).

I haven't dug into that discussion, but the [linked runc PR](https://github.com/opencontainers/runc/pull/3452/files#diff-63d5d4fb02e26ab3654fd242da5c22e44776c76b5aea357e15bc6a9e7193059aR15) doesn't actually drop ebpf, so ebpf's dependencies would still impact our dependency graph.

> If I understand correctly you never even execute c/ebpf code at the moment, so staying on an old version should be fine.

K8s can't stay on an old version once it picks up a runc using the new epbf version (which runc already did [at HEAD](https://github.com/opencontainers/runc/commit/83418f8878c1d171d56a5b1e6d1ba78726b6e128)).

Staying on old versions of unlinked/unused code also confuses security scanners with false positives about impact of reported issues with those old versions, so we try to avoid that (though hopefully scanners will start to use the approach taken by [govulncheck](https://pkg.go.dev/golang.org/x/vuln/cmd/govulncheck) which only reports issues in used code).

> Based on this, I'm inclined to keep the dependency on x/exp. You're correct that the current usage is limited, but I think the question here is not whether we can drop x/exp. Rather, this is about whether we want to abide by the k8s exclusion list.

`exp` gave enough explicit warnings in its documentation about the experimental/unreliable nature of the module to steer k8s away from depending on it. I was hoping you would be convinced of its unsuitability for the same reasons, not by k8s' exclusion list.

I'm disappointed with the willingness to pass `exp` on as a transitive dependency, but that's the ebpf maintainers' decision to make. If you do decide to keep it, I'd suggest mentioning use of `exp` in the readme next to the "It has minimal external dependencies" bit, to make it clear to folks evaluating taking a dependency on `ebpf` that it pulls in external dependencies that advertise themselves as experimental/unreliable.

> That said, if you do end up updating your minimum version we'll be responsive if a dependency on x/exp ever does break something.

I appreciate that, though we try hard to avoid putting maintainer responsiveness of all our dependencies in the critical path.

**Comment by lmb** [comment]
Thanks for providing more context. Sorry to hear that you won't be able to drop the dependency, that would've provided a good way out. Also interesting to hear re: vuln scanners.

> If you do decide to keep it, I'd suggest mentioning use of exp in the readme next to the "It has minimal external dependencies" bit, to make it clear to folks evaluating taking a dependency on ebpf that it pulls in external dependencies that advertise themselves as experimental/unreliable.

I think that's fair, but isn't the best source for this always go.mod? At least that is what I check first.

Like I mentioned, please reach out via slack or the issue tracker if necessary!

**Comment by liggitt** [comment]
Just wanted to comment here that this usage is surfacing again, and blocking Kubernetes updating _other_ dependencies now like cadvisor and hcsshim that pulled in newer ebpf versions with the exp dependency.

> We'll make sure to drop x/exp when those packages move back into the stdlib. 🙂

It looks like that already happened (🎉), and the only remaining use is of the `constraints` package.

I opened an updated version of https://github.com/cilium/ebpf/pull/1098 at https://github.com/cilium/ebpf/pull/1551, and included a unit test that will proactively detect new predeclared integer types so they can be added. Hopefully that can be merged to resolve this.
