### ISSUE TITLE
cilium/ebpf executes bpf syscalls during it's package init

### ISSUE THREAD

**Issue by korniltsev** [cilium/ebpf#1096]
**Describe the bug**

There are two places where bpf syscall is called

rlimit: https://github.com/cilium/ebpf/blob/main/rlimit/rlimit.go#L67
btf: https://github.com/cilium/ebpf/blob/main/btf/marshal.go#L27

I am trying to workaround it for grafana/agent  https://github.com/grafana/ebpf/pull/1 (any chance to get any feedback there as well? :) )

While the btf one is somewhat easy to fix, the rlimit one seems harder to fix because it looks like bpf syscalls are executed during init on purpose and it is not clear how to change it in a good way .
I wonder if cilium/ebpf will consider accepting PR's fixing the issues. If it's reasonable then we should probably discuss how to fix/implement it before creating PR's (at least rlimit part).

**To Reproduce**
- compile cillium/ebpf, but do not use it at runtime

**Expected behavior**
No bpf syscalls are executed

**Actual behavior**
Two bpf syscalls are executed in `rlimit` and `btf` modules

**Comment by korniltsev** [comment]
Just noticed btf one was fixed in 11 https://github.com/cilium/ebpf/commit/20c4d8896bdde990ce6b80d59a4262aa3ccb891d

**Comment by korniltsev** [comment]
I wonder if we can just check kernel version with uname? (maybe not in the cilium/ebpf, but the grafana agent)

Do you know any downsides of it? 

Are you aware of any kernel/distro which is >= 5.11 and has no bpf memcg accounting patches in it?

**Comment by korniltsev** [comment]
> Maybe you can tell me why it's a problem?

The problem is that grafana agent has configuration and depending on configuration it may do a ton of stuff, collect metrics, talk to kubernetes, and now ebpf profiling. And it seems strange and unneeded to do the bpf syscalls if the application is not configured to do ebpf.
I personally dont think this is a huge problem because I know the syscall does nothing. But others are "scared" because of "security reasons". (I put quotes because I dont agree).  

> Check the kernel version to do what exactly?

to make decision if the memcg accounting is available.

> Keep in mind that for example Red Hat produces frankenkernels

Yeah, I am not aware of any specific problems with redhat but scared of them in advance. 

Do you think this is a reasonable fix for our usecase?
https://github.com/grafana/phlare/pull/859

**Comment by lmb** [comment]
Okay, thanks for the context. The function runs on init because it's only safe to do the test during startup when as little code as possible is executing. Maybe there is a better way to achieve that instead of using `init`? Open to ideas.

**Comment by ti-mo** [comment]
@korniltsev Executing `detectMemcgAccounting()` after init() is not safe for a few reasons. I thought our doc comment in rlimit.go:init() was clear, but it does hand-wave over the specific reason why it's unsafe.

As you've identified in the PR in your fork, there's the call to `unix.Prlimit()` that can race with other packages, but the bigger issue is (temporarily) setting RLIMIT_MEMLOCK to 0 on kernels without memcg accounting. This will make all map creations fail in between both calls to Prlimit(), so any concurrent map creations will also fail.

This is less of an issue if all map creations become gated behind a sync.Once, but the design was always about making setting rlimit optional by way of an `rlimit` import side effect. Since all calls to init() are serialized across all packages, this is expected to be safe. As library authors, we cannot run the risk of this going wrong, so we must err on the safe side.

In your place, I'd have a conversation with your security team. It sounds like FUD, but I do agree that it's unexpected. Code is a liability, though, so as long as a binary contains the necessary code to interact with the bpf subsystem, for an attacker it's just a matter of twiddling the necessary flags to reenable ebpf profiling and you're back to square one.

Assuming you control Phlare's distribution mechanism (e.g. OCI/Docker containers), why not just give it an ambient `--ulimit memlock=-1`? (or set it in a Helm chart if ebpf profiling is enabled?) Package rlimit is really just for convenience, don't feel obliged to use it.

**Comment by korniltsev** [comment]
>  I thought our doc comment in rlimit.go:init() was clear,

It is. It is clear and helpful. I fully understand reasoning, especially for a library.

In the grafana agent there's no concurrent map creation and the rlimit package is the only place touching rlimit, so I should be safe.

> Assuming you control Phlare's distribution mechanism

We kinda control, but not all the time.  This may complicate the configuration, and then someone again may complain why we raise the limit when we dont'  even need it. 

> why not just give it an ambient --ulimit memlock=-1

Oh I have not thought about it, thanks a lot, will think about.

Anyways, thanks a lot for feedback. 
I am not intending to attempt to change rlimit implementation in the upstream because I don't know how to make it safe.

**Comment by lmb** [comment]
I'm going to close this issue since the check works as intended, we don't know of a better solution and there are workarounds.
