### ISSUE TITLE
Populate inner maps from BTF .values

### ISSUE THREAD

**Issue by takehaya** [cilium/ebpf#112]
Hi. thanks for the great project! 👍

I've been developing using the library since newtools/ebpf. 

I tried to switch to cilium/ebpf and found that the support for innermap was not complete realize.

For example, This function doesn't seem to take into account the fact that it is innermap.
https://github.com/cilium/ebpf/blob/7acf5cc039f43cc55e927f1c4b2fd161535aad26/elf_reader.go#L371

Do you plan to support innermap in the future?
If no one else is planning to do it, I'd like to help with that myself:)

**Comment by lmb** [comment]
Hi takehaya, I'm glad you find it useful :)

We use nested maps in our internal code base, so the library supports it in general. I think what you're running into is that you can't populate Map.InnerMap from within the ELF.

If you'd like to contribute this feature you could start by figuring out how to specify inner maps with libbpf. Since we try to be compatible with that it'd be good to check what their approach is. Once you know that I can point you at the right places in the code if needed.

**Comment by takehaya** [comment]
Hi Imb, thanks for replying!
Thanks for the great advice!

okay, let's look at the libbpf implementation.
I'll write about it when I understand it:)

**Comment by ti-mo** [comment]
There is one example of map-in-map autopopulation in the kernel tree (`map_perf_test_kern.c`):

```c
struct inner_lru {
	__uint(type, BPF_MAP_TYPE_LRU_HASH);
	__type(key, u32);
	__type(value, long);
	__uint(max_entries, MAX_ENTRIES);
	__uint(map_flags, BPF_F_NUMA_NODE);
	__uint(numa_node, 0);
} inner_lru_hash_map SEC(".maps");

struct {
	__uint(type, BPF_MAP_TYPE_ARRAY_OF_MAPS);
	__uint(max_entries, MAX_NR_CPUS);
	__uint(key_size, sizeof(u32));
	__array(values, struct inner_lru); /* use inner_lru as inner map */
} array_of_lru_hashs SEC(".maps") = {
	/* statically initialize the first element */
	.values = { &inner_lru_hash_map },
};
```

Note that in this case, the type of the inner map (`inner_lru`) and its structure variable (`inner_lru_hash_map`) have named references. I'll look into how this could be written using anonymous structs, I'm not sure if clang supports re-declaring an identical anonymous struct inside the `.values` assignment, but we might need to take this case into account.
