### ISSUE TITLE
Request: tagged releases

### ISSUE THREAD

**Issue by AkihiroSuda** [cilium/ebpf#115]
Any chance to have tagged releases?

**Comment by lmb** [comment]
There's nothing specifically preventing us from tagging a release, except that I'm not sure what the value is and at which point we should then tag follow up releases.

Can you describe your needs a bit more?

**Comment by AkihiroSuda** [comment]
Just to make `go.mod` in downstream projects look better 😅

**Comment by kolyshkin** [comment]
Having a tagged releases is basically a way to say "this is the version we want everyone else to use". Currently everyone is using whatever is available from master at the time of adding a dependency, which makes it kinda random, and is not ideal since the code might contain bugs etc.

**Comment by lmb** [comment]
The thing I'm most unsure about is when we would tag a new release. Seems like we always want a release when landing a bug fix. But not always when adding a feature? At which point do we have enough features? This also implies that we might have to "release" a feature because we need to get a bug fix out. Is that a problem?

> Currently everyone is using whatever is available from master at the time of adding a dependency, which makes it kinda random,

So the "random" bit is interesting. If we tag releases users will mostly end up on the same commit, so if there is a bug there
are less candidates to look at? At the same time discovering that a bug has been fixed on master requires explicit opt in via `@master`.

> and is not ideal since the code might contain bugs etc.

But then the same is true for any release we will tag. It's not like there is some magic process that we can run before doing a release that makes bugs go away.

I've been looking around for articles that talk about this subject, but I've not had much luck yet. I appreciate any pointers!
