### ISSUE TITLE
Kernel version detection does not work with vDSO disabled

### ISSUE THREAD

**Issue by Vyom-Yadav** [cilium/ebpf#1408]
### Describe the bug

```markdown
Automatic detection of Kernel Version is not supported without vDSO.
```

### How to reproduce

- Disable `vDSO` on a machine.
- Reboot the machine.

```
root@docker-vdso-test:~/ebpf-main# go test -v ./internal -run TestCurrentKernelVersion
=== RUN   TestCurrentKernelVersion
    version_test.go:53: finding vDSO memory address: no vdso address found in auxv
--- FAIL: TestCurrentKernelVersion (0.00s)
FAIL
FAIL	github.com/cilium/ebpf/internal	0.004s
FAIL
```

### Version information

main

**Comment by Vyom-Yadav** [comment]
For why support without vDSO is required, see: https://github.com/cilium/ebpf/pull/1399

**Comment by lmb** [comment]
Can you explain how you disable vDSO please?

**Comment by Vyom-Yadav** [comment]
I referred to this: https://stackoverflow.com/q/8280014

**Comment by lmb** [comment]
There are three different ways of "disabling" vDSO in that post. One of them strips the auxv, which is what we use. I need to know which one you're using / expect to work.

**Comment by lmb** [comment]
Seems like `vdso=0` causes the kernel to [omit `AT_SYSINFO_EHDR` on am64](https://elixir.bootlin.com/linux/v6.8.2/source/arch/x86/include/asm/elf.h#L336). On arm64 the header is [emitted unconditionally](https://elixir.bootlin.com/linux/v6.8.2/source/arch/arm64/include/asm/elf.h#L170) (maybe because arm64 doesn't allow turning of the vdso?)

My conclusion is that turning off the vdso is still kind of esoteric, and not something I want to spend a lot of effort supporting. I definitely don't want to bring back uname parsing. It also seems like it's possible to [intercept gettimeofday using ltrace](https://stackoverflow.com/a/38129286), so there is at least one possible work around.

If you really want this to work with vDSO off I can only offer you a partial work around. You can adjust https://github.com/cilium/ebpf/blob/a330a78da8cbdbc75d55afac577f92dc0da4bc90/prog.go#L253 to only call `internal.KernelVersion` on old kernels (< 5.0) by writing a feature test (see haveProgRun in prog.go for inspiration) which checks whether the kernel requires KernelVersion to be present for Kprobes.

**Comment by ti-mo** [comment]
Sorry, this situation is unlikely to change until we drop support for pre-5.0 kernels. If there are any other ideas aside from uname parsing, I'm all ears. Closing for now.
