### ISSUE TITLE
Formalize contributing guide

### ISSUE THREAD

**Issue by joestringer** [cilium/ebpf#184]
We had an interested developer join the weekly Cilium community meeting looking to understand the contribution process for submitting changes into this library.

Github acknowledges a file named `CONTRIBUTING.md` in the root of any repo and adjusts the UI to highlight that process, we could add such a file to clarify the process for new contributors.

There are probably better examples elsewhere, but at least for Cilium it points towards the main Cilium documentation page on contributing (https://github.com/cilium/cilium/blob/master/CONTRIBUTING.md -> https://docs.cilium.io/en/stable/contributing/development/contributing_guide/). I don't believe it makes sense to inherit these into the process for this library as the needs of contributors and the development requirements are vastly different.

**Comment by ti-mo** [comment]
@joestringer Thanks for dropping an issue!

I've found some more example contribution guidelines here: https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/setting-guidelines-for-repository-contributors#examples-of-contribution-guidelines. The guidelines here don't need to be too elaborate, but could specify things that would otherwise be mentioned during review.

The community member on the call asked about:
- whether accompanying tests need to be contributed in order for a patch to be accepted
- commit/code style
