### ISSUE TITLE
perf event arrays should be useable out of the box

### ISSUE THREAD

**Issue by lmb** [cilium/ebpf#209]
Using a perf event array with a `perf.Reader` is error prone at the moment, since you need to declare your PERF_EVENT_ARRAY with max_entries == 0 so that the library figures out the # of possible CPUs. This has bitten at least @tqbf and @hariharan-a.

The library used to reject PERF_EVENT_ARRAY that didn't have max_entries == 0, but that broke for people trying to load kernel selftests.

Maybe we can find a behaviour that makes the common case work out of the box. We can check what libbpf does. If they don't have anything sensible either we can at least improve the documentation.

**Comment by Houwenda** [comment]
Came across a compatibility problem related to libbpf and perf.NewReader.
I defined a PERF_EVENT_ARRAY with max_entries greater than the CPU counts on my machine. My C program loaded the map and pinned it, allowing another program to load and read from it.
I implemented the function of reading events both in C and Go. Libbpf worked perfectly with the pinned map but this package didn't, resulting in an error of EINVAL. 

I find out that libbpf first compares max_entries (if not zero) with possible CPU count, using the smaller one to create CPU buffers in a loop (ignoring the offline CPUs, which this package does as well) . So using this perf event array with libbpf will not result in an error.

Perf.NewReader, instead, will try to create buffers based on max_entries. Since the requested CPU does not exist, syscall returns with EINVAL.

I can get around this problem by leaving max_entries as default(0), so libbpf will automatically use the available CPU count as the max_entries during loading, and this package can then get the correct max_entries from pinned map.

Maybe we should use the method from libbpf to make ebpf.NewReader more compatible? 

I think my case is related to this issue. Sorry if I didn't explain it clearly.

**Comment by ti-mo** [comment]
> Maybe we should use the method from libbpf to make ebpf.NewReader more compatible?

Yes, I think this is definitely something we should address. I think libbpf's behaviour around this is sane, and I don't really see a reason to do things differently.

**Comment by lmb** [comment]
> I think libbpf's behaviour around this is sane, and I don't really see a reason to do things differently.

As I understand it, the libbpf behaviour will lead to BPF programs silently dropping samples on high numbered CPUs if the perf_event_array is < number of CPUs in the system. I think that's bad. I also don't know of a use case where specifying the number of CPUs in the ELF makes sense. Maybe I'm missing something?

So really, there are only two valid values for max_elems from my POV: 0 or MaxUint32. I see these options:
* Go back to the old semantics and enforce `0` (and `MaxUint32` if that is used in practice), assign the correct number in the ELF reader.
* Ignore max_elems from ELF definitions and always assign the correct number of CPUs in the ELF reader.

**Comment by lmb** [comment]
Ok, I'm wrong: I've only ever used `bpf_perf_event_output` with `BPF_F_CURRENT_CPU` in which case a too small perf event size is problematic. If you skip flags to perf_event_output, a perf array with only a single item is valid. The kernel selftests have a bunch of cases that write to perf event buffers on CPU 0 for example. Some also call bpf_perf_event_reads similarly.

So we should do the min(max_elems, CPUs) logic.
