### ISSUE TITLE
MapABI should contain Flags

### ISSUE THREAD

**Issue by joestringer** [cilium/ebpf#30]
Cilium propagates a user option to determine whether to pre-allocate the memory for entries in maps that support it, using the `bpf_attr.map_flags` field. To support this option in Cilium, we would need to allow this to be configured somehow (presumably in `MapABI`?)

Related comment on prior PR: https://github.com/cilium/ebpf/pull/27#discussion_r342486870

**Comment by lmb** [comment]
MapABI is currently only used by user code to verify that it's dealing with the maps its expecting. When creating we use MapSpec (somewhat confusingly I guess), which already has `Flags`.

How do you want to use MapABI.Flags?

**Comment by joestringer** [comment]
I think that the `MapABI` vs `MapSpec` is and will continue to be a source of confusion unless there are clear examples and descriptions for them.

Note the current descriptions:

https://github.com/cilium/ebpf/blob/50dad17607417dcf1a70ff581a7d81fbabda6ae9/abi.go#L56-L65

https://github.com/cilium/ebpf/blob/50dad17607417dcf1a70ff581a7d81fbabda6ae9/map.go#L13-L25

When I look at the actual exposed usage of MapABI in public functions of the library, the initial reason I thought I might need it is because of `map.go:func LoadPinnedMapExplicit(fileName string, abi *MapABI) (*Map, error)` which I previously needed to use for the perf reader. That's not necessary any more.

I think we'll need to take another look at this from an upgrade/restore perspective as we look to migrate Cilium over to this model. In my mind, I have it that someone could deploy Cilium defining that Cilium should minimize memory usage which would disable preallocation of map elements, then they could change the setting to minimize latency, enabling preallocation of map elements where available and then restart Cilium. In that case, I'd imagine some piece of code responsible for map handling upon startup to scan across all of the existing maps and check that the flags match the setting (then recreate the maps if they don't match). At the moment, that code is largely handled by a separate map upgrade handling program which we run prior to the loader that we currently run, but long term I hope that all of that code can be switched over to this library instead.

**Comment by lmb** [comment]
There are two reasons MapABI exists:

1. Define a template that user code can use to match against an actual map using Check. The zero value of the MapABI.Type, etc. is treated as "don't care what the value is" by Check, so that users can check only some fields.
2. It's not possible to get all the fields in MapSpec from the kernel. The biggest problem are nested maps, where I don't know how to get the InnerMap. Same goes for Name.

I'm not super convinced that (1) is actually terribly useful. In our code we mostly make sure that maps have the type we expect. What is useful is CollectionABI.Check(Spec) which allow you to skip checking for the presence of maps / programs when using a Collection(Spec). We could get rid of MapABI.Check, ProgramABI.Check, and simplify / get rid of CollectionABI.

I don't think (2) is fixable. Which implies that there has to be the distinction between Spec and ABI, but we need to make it clearer somehow. Maybe we can give it a better name? Another problem is that #27 means that *ABI can't contain more fields than what /proc gives us, but people would like more fields added to it (see #26).

**Comment by joestringer** [comment]
Re (1) above: In Cilium, the importance of an individual map may vary, some we're happy to just throw away and recreate; others if we are going to delete it, we will want to manage the deletion to prevent loss. From that perspective if we have a way to determine "out of the collection ABI, maps X and Y are fine but Z doesn't match" then we could potentially write that special map-handling logic around that. That may or may not require the actual `MapABI.Check` though.

(2) seems like it could do with some good ol' fashioned kernel grease to ensure that the info about the inner map is propagated. From my reading, the map-in-map structures in the kernel do actually hold the entire inner-map metadata so in theory there should be a way to export it.

I'm not against having the ABI / Check functionality, in some sense we actually have similar freeform logic in Cilium, see `objCheck()` below; I just haven't spent enough time looking at it yet to form a strong opinion about what this should look like. If there's an intermediate period where we get rid of it, then rethink it from scratch, I'm OK with that; if we keep it and review it when Cilium folks try to get rid of `objCheck()`, that's fine too.

https://github.com/cilium/cilium/blob/a5f4964488672feed0ca07cd124202888070f84d/pkg/bpf/bpf_linux.go#L366

**Comment by lmb** [comment]
Ok, it's good to know that `Check` exists in Cilium as well. Getting back to this issue in particular: adding map_flags only works if we rework `Check` into `Equal` and drop the ability to compare only some fields. This is because people might want to check that map_flags == 0.

Re (2), I've created #31 to track fixing the inner map problem.

Overall, the complexity here stems from the fact that we're trying to paper over kernel API deficiencies and it reminds me a lot of the MapIterator discussion. Maybe MapABI needs to go away, to be replaced with MapInfo that just mirrors the kernel's object info. Which implies that there should be a MapFDInfo as well, with the contents of #27. Sigh.

**Comment by joestringer** [comment]
Yeah, I think there's a couple of cases where `MapABI` make sense to me -- particularly for instance when you look at map-in-map handling and having a notion of what kind of map can be placed into the other map. But in that case you can likely achieve the abstraction you want with something like:

```
mim := LoadPinnedMap(...) // MapInMap
foo := NewMap(...) // Random map
if mim.Accepts(foo) {
    mim.Update(key, foo)
} else {
  // log? Recreate the map-in-map so it will accept foo?
}
```

Whereas for this other entire set of functionality like what people want in #26, or what the previously mentioned Cilium `objCheck` logic does, then you probably just want to look at a map and get as much info as you possibly can, and potentially write whatever your own logic is on top of those. The basic `Equals()` functionality would be great, then if anyone wants something more nuanced then the `MapInfo` fields can be public.

The idea of `MapInfo` vs. `MapFDInfo` sounds a bit confusing to me. What would you envision to be the primary usage or differences between `MapInfo` / `MapFDInfo` / `MapSpec`? Do we really need three different notions of the essentials of a map?

**Comment by lmb** [comment]
Yeah, `MapFDInfo` is a bad idea. I spent some more time with the code yesterday. We need the following types, I believe:

1. A type that describes a map to be created from scratch (MapSpec)
2. A type that is the minimum information required when loading a pinned map (currently MapABI). If we want to support older kernels, this has to be the intersection of what is available in /proc and OBJ_GET_INFO, and therefore excludes nested maps.
3. Whatever OBJ_GET_INFO returns (currently doesn't exist).

We can decide that (2) is going to be an implementation detail and hidden from the end user. However, that just means users will have to re-implement the functionality. We can also decide that (3) is out of scope of the package and relegate it to some syscall wrapper or such. This will probably confuse users.

**Comment by joestringer** [comment]
(2) and (3) above seem to have quite a bit of overlap. For one thing (3) should be a superset of (2). Maybe with sufficient documentation we can compose (3) from (2) and describe the `MapABI` as the minimal attributes of a map that are guaranteed to be available on all kernels; meanwhile the `MapInfo` is more comprehensive but some fields may be empty depending on kernel support..

Which starts to lead us in the direction of detecting kernel support so you can know whether to trust the fields in the `MapInfo` that you dump... ;)

**Comment by borkmann** [comment]
[...]
> (2) seems like it could do with some good ol' fashioned kernel grease to ensure that the info about the inner map is propagated. From my reading, the map-in-map structures in the kernel do actually hold the entire inner-map metadata so in theory there should be a way to export it.

It's possible. map-in-map types support lookups via syscall. You get the inner map id from there. Then you can fetch an fd for this inner map id, and do the get_info_by_fd on the map. All inner maps must have same meta info (key/val size, # elems, etc) since they can be replaced atomically.

**Comment by lmb** [comment]
From what I can tell this doesn't work for an empty map though?
