### ISSUE TITLE
eBPF for windows

### ISSUE THREAD

**Issue by massoudasadi** [cilium/ebpf#319]
is there any plan to support eBPF for windows ?

https://github.com/microsoft/ebpf-for-windows

**Comment by lmb** [comment]
That is currently unlikely I'd say, unless eBPF on Windows replicates the Linux syscall boundary.

Neither Cloudflare nor Cilium deploy to Windows at the moment, so there is little incentive for us to do the work. Maintaining it would also require finding a suitable CI, which isn't easy. Not saying it can't happen, but it would require a serious commitment of time.

**Comment by ti-mo** [comment]
Good question, but too little is known at the moment to give this question an honest in-depth answer. Aside from the points raised by @lmb, it's simply not clear _what_ needs to be done in order to 'support' Windows. The Windows eBPF project is still in its infancy, is being worked on by a relatively small team, so I would expect a few things to shift around over the course of the coming months/years.

At its core, the loader infrastructure (though I doubt a Windows eBPF compiler would emit ELFs) and assembler should be usable to generate eBPF bytecode for Windows, but the rest will likely differ a great deal between Windows and Linux. I have no clue what the Windows syscall API looks like, and it looks like the Windows verifier runs at least partially in userspace.

Also, it's not clear what eBPF on Windows will be used for. (to me, at least)

MS being what they are, I would expect them to ship their own .NET-flavored toolchain to become productive on Windows systems, and all other languages will likely trail behind by several year(s) as they catch up on reverse-engineering or implementing the APIs from enterprise documentation.

Closing this for now as there's nothing actionable today, let's re-open if/when this is discussion can be resumed at a later stage.

**Comment by ti-mo** [comment]
Good question, but too little is known at the moment to give this question an honest in-depth answer. Aside from the points raised by @lmb, it's simply not clear what needs to be done in order to 'support' Windows. The Windows eBPF project is still in its infancy, is being worked on by a relatively small team, so I would expect a few things to shift around over the course of the coming months/years.

At its core, the loader infrastructure (though I doubt a Windows eBPF compiler would emit ELFs) and assembler should be usable to generate eBPF bytecode for Windows, but the rest will likely differ a great deal between Windows and Linux. I have no clue what the Windows syscall API looks like, and it looks like the Windows verifier runs at least partially in userspace.

Also, it's not clear what eBPF on Windows will be used for. (to me, at least) If there is an open-source loader implementation in another language, we could consider implementing it, but for now I personally remain skeptical.

Closing this for now as there's nothing actionable today, let's re-open if/when this is discussion can be resumed at a later stage.
