### ISSUE TITLE
Is there a plan to support af_xdp with binding ringbuffer operation？

### ISSUE THREAD

**Issue by glennWang** [cilium/ebpf#338]

**Comment by ti-mo** [comment]
Hi @glennWang, could you provide a bit more context about the functionality you're looking for?

**Comment by lmb** [comment]
I'm closing this for now, since it's not clear what the scope should be. If you disagree, please file a feature request that specifies:

* What features you want supported
* What your use case is
* Whether you are willing to contribute support / maintain the feature going forward

Just opening an issue without a description **is not enough**. We (Cloudflare) currently don't need AF_XDP support so won't be working on it.

**Comment by glennWang** [comment]
@ti-mo @lmb 

Please forgive me for my mistake.

I wang to process packets on user space.

For example, develop a high performance udp server basied on af_xdp socket.

**Comment by ti-mo** [comment]
@glennWang Is this a feature you could contribute? If parts of the library are useful for building something like this, we would definitely be open to accomodating this use case. However, in order for that to happen, we need to know what this sort of API would look like, what its requirements are, and what its possible use case would be. Without this, we cannot help you design or propose a solution.

As Lorenz indicated above (to add some nuance), neither Cilium nor Cloudflare currently have a use case for af_xdp, so we're unlikely to come forward with a proposal of our own.

Our understanding of 'high performance udp server' may vary, but I'm not entirely sure if I would look at Go as a primary candidate for building this type of application -- of course that doesn't mean it can't be done for certain use cases.

**Comment by crandles** [comment]
👋  this project may be of interest: https://github.com/asavie/xdp -- it uses cilium/ebpf to build an AF_XDP program, attach it to an interface, and has go bindings around the necessary kernel APIs to create a ring buffer for reading or transmitting packets.
