### ISSUE TITLE
Add BPF ringbuffer example to examples/

### ISSUE THREAD

**Issue by ti-mo** [cilium/ebpf#396]
Following comment https://github.com/cilium/ebpf/pull/318#discussion_r699770055, we should add a ringbuf example once #318  is merged.

cc @folbricht

**Comment by Pippolo84** [comment]
Hi!

Since I am learning BPF programming and experimenting with this library, I have written such an example.

The BPF program I used to exercise the RINGBUF map type is very similar to [this one](https://github.com/grantseltzer/libbpfgo-example).

I'll open the PR, let me know what you think, I am happy to make any changes, if needed.
