### ISSUE TITLE
bpf2go: strip dwarf debug symbols from ELF

### ISSUE THREAD

**Issue by lmb** [cilium/ebpf#429]
From https://nakryiko.com/posts/libbpf-bootstrap/#makefile we can strip dwarf symbols from the compiled .o via `llvm-strip -g` resulting in a smaller ELF.

- Would we need a command line option to override `llvm-strip`?
- How much of a difference does stripping make?

**Comment by ti-mo** [comment]
```
-rw-r--r-- 1 timo timo 4.3K Aug 10 13:04 invalid_map_static-eb.elf
...
λ  ebpf/testdata master ✓ llvm-strip -g invalid_map_static-eb.elf
...
-rw-r--r-- 1 timo timo 2.0K Sep 22 10:06 invalid_map_static-eb.elf
```

Looks worth it. :)

> Would we need a command line option to override llvm-strip?

What do you mean?

**Comment by lmb** [comment]
We have `-cc` to change which clang we use, do we need a `-strip`?

**Comment by ti-mo** [comment]
Oops, didn't notice this issue was about bpf2go specifically.

I'm not sure if DWARF info should be kept around if it's so heavy, at least not if it already containts BTF info.

A quick search taught me GDB recently got an eBPF simulator, so what about inverting this behaviour with a `-debug` flag or similar instead? Strip DWARF by default, but allow preserving it explicitly.
