### ISSUE TITLE
Removal of `btf.Program`

### ISSUE THREAD

**Issue by ti-mo** [cilium/ebpf#522]
Currently, a program's BTF info is kept in a separate structure, pointed to by `ebpf.ProgramSpec`'s `BTF` field. Now the use case for BTF has grown as substantially as it did, it's time to merge this data structure into the core types for ease of maintenance.

Having this in a separate structure is both convenient (checking BTF presence is checking a single value) and inconvenient in some ways, but overall it's a burden to have the data spread out between two structs, especially when it comes to marshaling BTF info back into binary form.

My initial idea is to move things around as follows:

- FuncInfo: remove in favor of a `btf.TypeID` field in `ebpf.ProgramSpec`
- LineInfos: resolve file and lineinfo into strings, move to `ebpf.ProgramSpec`, exported (?)
- CoreRelos: not quite sure what to do with this yet, could be moved and unexported initially

https://github.com/cilium/ebpf/pull/508 already made some small steps to remove the need for `FuncInfo` and `LineInfo` to resemble their wire formats so closely. Ultimately, we should end up with something like `[]*ProgramSpec.MarshalFuncInfos()`.

More suggestions:
- https://github.com/cilium/ebpf/pull/508#discussion_r760258743: export `coreRelocate` and get rid of `Program`?
- https://github.com/cilium/ebpf/pull/508#discussion_r760271764: Why not have `FuncInfos.Marshal`?
- https://github.com/cilium/ebpf/pull/508#discussion_r760269474: Store `Type *Func` instead of bare TypeID

**Comment by lmb** [comment]
We could solve many of these with flexible metadata in `asm.Instruction`, then concatenation of `asm.Instructions` does the right thing by default. There is a proof of concept for per insn metadata in 483ca4a65c08a117afcd25cc65e5407a27972762, but I think a real implementation needs to be more flexible, `instructionMeta` should probably be a `map[interface{}]interface{}` and work similarly to context.Value. We'd also need copy on write semantics. With that in place:

* `LineInfos` could become metadata on `asm.Instruction` pretty easily.
* `FuncInfo` could also become per insn metadata, but this is less straighforward.
* `CoreRelos` could also become per insn metadata, but we'd still have to collect all relos into a slice, see `coreRelocate`.
* We could solve #515 and #517 by adding metadata that references a `*Map`. This could also allow `NewProgram(CollectionSpec.Programs["foo"])` to resolve maps, which currently returns an error.

We shouldn't support the user creating `FuncInfo` etc. metadata to start with. `FuncInfo`, `LineInfo` is basically kernel wire format, and we shouldn't really be exposing that.

The downside to this schema is that per insn metadata only works well if most instructions don't have metadata, to keep the overhead low. It's also pretty pointer / indirection heavy. However stuffing things like `uint64` into an `interface{}` is probably pretty cheap since we don't need memory beyond the two words for the interface. And for certain things like `*Map` we can't avoid the pointer in the first place, since we need it to prevent the finalizer from running. Put another way: in terms of efficiency we can't get much better than `[]FuncInfo`, etc. along side `asm.Instructions`, but that comes at a code complexity cost since we need to keep track of function offsets manually.

**Comment by lmb** [comment]
I've put my WIP metadata implementation here: https://github.com/lmb/ebpf/commits/issue-515-instruction-meta
