### ISSUE TITLE
link: get info from FD

### ISSUE THREAD

**Issue by Asphaltt** [cilium/ebpf#967]
Currently, there is no way to get link information from FD, like the way for bpf map and bpf prog.

What I expect is `link.GetLinkInfoFromFD()`, not `link.LoadLinkFromFD()`.

```Go
func GetLinkInfoFromFD(fd int) (*Info, error) {
	dupFD, err := syscall.Dup(fd)
	if err != nil {
		return nil, fmt.Errorf("failed to dup the FD: %w", err)
	}

	sysFD, err := sys.NewFD(dupFD)
	if err != nil {
		_ = syscall.Close(dupFD)
		return nil, err
	}

	link := &RawLink{fd: sysFD}
	defer link.Close()

	return link.Info()
}
```

The user case behind it is that I want to check the bpf-related FDs in application process with those bpf objects pinned under bpffs in order to confirm whether there are leaked bpf-related FDs in application process.

**Comment by lmb** [comment]
`link.LoadLinkFromFD()` isn't a thing right now, but is probably the way to implement this if you're up for it.

Why do you want `GetLinkInfoFromFD` instead of `LoadLinkFromFD` though?

**Comment by Asphaltt** [comment]
> Why do you want `GetLinkInfoFromFD` instead of `LoadLinkFromFD` though?

I don't like the way of `NewMapFromFD()` and `NewProgramFromFD()` that breaks the original FD.

Why not `syscall.Dup()` in `NewMapFromFD()` and `NewProgramFromFD()`, as well as `NewLinkFromFD()` ~~LoadLinkFromFD()~~.

```Go
func NewLinkFromFD(fd int) (Link, error) {
	dupFD, err := syscall.Dup(fd)
	if err != nil {
		return nil, fmt.Errorf("failed to dup the FD: %w", err)
	}

	sysFD, err := sys.NewFD(dupFD)
	if err != nil {
		_ = syscall.Close(dupFD)
		return nil, err
	}

	return wrapRawLink(&RawLink{fd: sysFD})
}
```

Then, I am able to get link info with `NewLinkFromFD()`.

**Comment by Asphaltt** [comment]
I get the fd from listing `/proc/self/fd`.

**Comment by lmb** [comment]
Right. Your problem stems from the fact that you want to create two references to the same fd. That doesn't play well with ownership semantics of `os.NewFile` and `NewLinkFromFD`. Your use case is kind of "unsafe" I'd say, so it's up to you to arrange things in a way that you don't break the application, aka dup the fd.

We can add `NewLinkFromFD` with the same semantics as `NewMapFromFD` and you'll have to do the dup'ing yourself. (You probably want to use fcntl F_DUPFD with O_CLOEXEC instead of Dup.)
